travis:
  secure:
    BINSTAR_TOKEN: hP8l2jBapitRhi28u5pog58zM+O31/nqcRC35Mykx14z2UJo4oPIVvFjvs+9YkCFUr/+BhyCbj5FwBgPzxr5Ekgn59wYGVlzkTSY8z6b1UnC0HpDzUuDs8ThMsolCtMkO8ineoL1YrKDKDecqIAWJA4SXqutyuzIzJBTGAxEZt32nBc9IabzHcCVvYHOqI3dQsqLnonUdMs4fAPwvjKjP3k66cO2eIqHPA+ChhIRMNMXd3mhmeoNzvZtFVLvrSYrB/Ghf24v0DhXkUfufeX0VO2Ci7wwGXMHagvVSEkX0cQ4QcIMOvsgM0xXtHzQxuNDMjwhlALwC0SakVs6t96GxOps/VIpPWBKR/vog7dnJ+xvVOb7t2GI8lq0vc6CuGxpczF/IdZe9izsaX57Lx89f5cyOTU2ywAW3zNe9eU+BXvyAbOfpg3KzfgtlZtPJVvH9zQ7am5okfSiGtAX0rqT3bvXzzIFdrUcnoe/foTJhRqbjwZHSEaJDRPe6yySJF5Cd6dl9M0xe7K9ysZC/CDpKsUUWbdg8lm1rRS7YbcQoYs9PReiyj4uPGQRqDO587qTaZAIVPjwz1xI6GMosFqmfRhnKmVU3KqX/MamiNKHBr39gqTlQklfDq0UMD5/u2D9YwixX4cUtDVp2gmRJR/58mWTJnp9ruKyPKqOtTSIAnM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
